---
title: "r notebook"
output: html_document
runtime: shiny
---

```{r,message=FALSE,echo=FALSE,warning=FALSE}
source(file.path('.','library.R'))
```

```{r,message=FALSE,echo=FALSE,warning=FALSE}
source(file.path('.','read_kaggle_housing_data.R'))
```

```{r}
find_fields <-function(d,target_type_of = 'character'){  
  #' Identify fields in a data frame of a selected type_of
  #' 
  #' @param d The data frame
  #' @param target_type_of The type_of for fields selected.
  t_types <- sapply(d,type_of)  
  return(t_types == target_type_of)
}
numeric_character <- function(d,num_distinct = 30){  
  #' Identify the fields that could be either nominal or interval.
  #'
  #' \code{numeric_character} If a field of type integer or double has less than num_distinct
  #' levels, it might be nominal and not interval
  #' @param d The data frame
  (sapply(t,'n_distinct') <= num_distinct) & (sapply(t, type_of) %in% c('integer','double'))
}
possible_class<-function(d,num_distinct = 30){
  #' Identify fields the could be nominal
  #' 
  #' @param d The data frame
  #' @param num_distinct Fields with less distinct levels might be nominal
  (sapply(t,'n_distinct') <= num_distinct) 
}
```


```{r,echo=FALSE}
      selectinput("predictor","choose a predictor:",  
                  choices = names(t),selected = 'x1stflrsf' )

 #     plotoutput("plot",height = "100%", brush = "brush")  
```

```{r,echo=FALSE}
      selectinput("color","choose a color:",  
                  choices = names(t)[possible_class(d)],selected = 'salecondition' )
```

```{r,echo=FALSE,eval=FALSE}
d <- tribble(
  ~x,
  1,
  2
)
  
myexpression2 <- 'x'
f <- function(d,myvar,myexpression){
  d %>% mutate(!!myvar := as.character(!!rlang::sym(myexpression2)))
}

f(d,'y','x')
```


```{r,echo=FALSE}
data<-eventreactive(input$color,{
  #mosold
  t %>% mutate(!!input$color := as.character(!!rlang::sym(input$color)))
  })
```

```{r,echo=FALSE}
renderplot({ 
  ggplot(data(),aes_string(input$predictor,'salepricelog',color=input$color)) + geom_point() 
  })
```
```{r,echo=FALSE}
      selectinput("class","choose a class:",  
                  choices = names(t),selected = 'salecondition' )
```
```{r,echo=FALSE}
renderplot({ 
  ggplot(data(),aes_string(input$class,'salepricelog',color=as.character(input$color))) + 
    geom_violin()
  })
```
```{r,echo=FALSE}
      selectinput("predictors","choose a predictor:",  
                  choices = names(t),selected = 'x1stflrsf' , multiple = true)

 #     plotoutput("plot",height = "100%", brush = "brush")  
```

```{r,echo=FALSE}
my_model<-eventreactive(input$predictors,{ 
  my_formula <- paste0('salepricelog ~ ',paste(input$predictors,collapse = '+ ', sep=" " ))
  my_model <- t %>% lm(my_formula,.)  
})
```
```{r,echo=FALSE}
t_augment<- eventreactive(input$predictors,{
  my_model() %>% augment(type.predict = 'response',type.residuals = 'response',data=t) %>%
  mutate(model_resid = .resid) %>%
  mutate(influential = .cooksd > 4/length(salepricelog))
})
```
#################
```{r,eval=true,echo=FALSE}
renderplot({ 
  model_num = 1   
  num_of_canadate_features = 15 
  sig <- 0.0010 
  response <- "salepricelog"  
  t_types <- sapply(t_augment(),typeof)  
  keep_fields <- !(names(t_augment()) %in% c('SalePrice','Id')) 
  t_numeric_fields <- t_types[t_types != 'character' & keep_fields ] 
  t_numeric <- t_augment()[names(t_numeric_fields)]
  # Calculate the correlation matrix 
  res2 <- rcorr(as.matrix(t_numeric)) 
  res2_price_p <- res2$P[response,] 
  correlation_significant<-res2_price_p <= sig & !is.na(res2_price_p) 
  res2_price_r <- res2$r[response,]  
  features_significant <- res2_price_r[correlation_significant]  
  features_significant <- features_significant[order(abs(features_significant),decreasing=TRUE)] 
  remove_response <- !names(features_significant) %in% c('SalePriceLog',response) 
  features_significant <- features_significant[remove_response] 
  t_selected <- t_numeric %>% select(c(names(features_significant)[1:num_of_canadate_features],response))  
  t_selected %>% cor(use='pairwise.complete.obs') %>% corrplot.mixed(number.cex = 0.5,order = "AOE",tl.pos='lt')
})
```

```{r,echo=FALSE}
renderPlot({ 
  ggplot(t_augment(),aes_string('model_resid','SalePriceLog',color=input$color)) + geom_point() 
  })
```
```{r,echo=FALSE}
renderTable(my_model() %>% glance)
```
```{r,echo=FALSE}
renderTable(my_model() %>% tidy)
```
```{r,echo=FALSE,eval=FALSE}
renderTable(t_augment())
```






